name: Open release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  bump-commit:
    name: Bump version and commit
    runs-on: ubuntu-latest
    needs: [check, test, fmt, clippy]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-edit
    - uses: actions-rs/cargo@v1
      with:
        command: set-version
        args: ${{ github.event.inputs.version }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump version to ${{ github.event.inputs.version }}
        file_pattern: Cargo.toml

  open-pr:
    name: Open PR
    runs-on: ubuntu-latest
    needs: [bump-commit]
    steps:
    - uses: actions/checkout@v2
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: repo-sync/pull-request@v2
      with:
        pr_title: "Release ${{ github.event.inputs.version }}"
        pr_reviewer: "airuta"
        pr_assignee: "airuta"
        pr_label: "release"
        destination_branch: "main"
        github_token: ${{ steps.generate-token.outputs.token }}
