name: Publish

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token ${{ env.CARGO_TOKEN }}
    - name: Get version from Cargo.toml and tag the branch with it
      run: |
        PKG_VERSION = $(shell awk -F ' = ' '$$1 ~ /version/ { gsub(/[\"]/, "", $$2); printf("v%s",$$2) }' Cargo.toml)
        git tag -a $PKG_VERSION
